<?php

/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        Category
 * GENERATION DATE:  28.03.2018
 * FOR MYSQL TABLE:  oc_category
 * FOR MYSQL DB:     antsnab
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

/**
 * @category WS patches 
 * @package  WS
 */
/**
 * @copyright  Copyright (c) 2018 AntSnab. (https://www.ant-snab.ru)
 * @author     Sergey Lapshin (http://vk.com/wslapshin) 
 */

namespace WS\Domain\Category;

use WS\Domain\ADomain;
use Doctrine\Common\Collections\ArrayCollection;

class Category extends ADomain
{

    protected $category_id;   // KEY ATTR. WITH AUTOINCREMENT
    protected $image;
    protected $top;
    protected $column;
    protected $sort_order;
    protected $status;

    protected $date_added;
    protected $date_modified;
    protected $language_id;
    protected $name;
    protected $description;
    protected $meta_title;
    protected $meta_h1;
    protected $meta_description;
    protected $meta_keyword;

    protected $categories;
    protected $parCategory;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    //@task подумай, это вроде application bl 
    public function getHref(\Url $url)
    {
        $parts = array();
        $current = $this;
        while (null !== $current) {
            $parts[] = $current->category_id;
            $current = $current->parCategory;
        }
        $parts = array_reverse($parts);
        return $url->link('product/category', 'path=' . implode('_', $parts));
    }

    public function getImageUrl( $imageTool, $width, $height ) 
    {
       return $imageTool->resize($this->get('image'), $width, $height);
    }

    public function getMetaData()
    {
        
    }

    public function validate()
    {
        
    }

}

?>
