<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        Category
 * GENERATION DATE:  28.03.2018
 * FOR MYSQL TABLE:  oc_category
 * FOR MYSQL DB:     antsnab
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

/**
 * @category WS patches 
 * @package  WS
 */
/**
 * @copyright  Copyright (c) 2018 AntSnab. (https://www.ant-snab.ru)
 * @author     Sergey Lapshin (http://vk.com/wslapshin) 
 */

namespace WS\Domain\Category;

use WS\Domain\ADomain;
use Doctrine\Common\Collections\ArrayCollection;

class Category extends ADomain
{
    public $category_id;   // KEY ATTR. WITH AUTOINCREMENT
    public $image;
    public $top;
    public $column;
    public $sort_order;
    public $status;
    public $date_added;
    public $date_modified;

    public $categories; 
    public $parCategory;

    public function __construct($valueAr)
    {
        parent::__construct($valueAr);
        $this->categories = new ArrayCollection();
    }

    //@task подумай, это вроде application bl 
    public function getHref(\Url $url)
    {
        $parts = array();
        $current = $this;
        while( null !== $current ) {
            $parts[] = $current->category_id;
            $current = $current->parCategory;
        }
        $parts = array_reverse($parts);
        return $url->link('product/category', 'path=' . implode('_', $parts));
    }


    public function getMetaData()
    {
        
    }

    public function validate()
    {
        
    }

}

?>
