
<?php

/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        Review
 * GENERATION DATE:  30.03.2018
 * FOR MYSQL TABLE:  oc_review
 * FOR MYSQL DB:     antsnab
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

/**
 * @category WS patches 
 * @package  WS
 */
/**
 * @copyright  Copyright (c) 2018 AntSnab. (https://www.ant-snab.ru)
 * @author     Sergey Lapshin (http://vk.com/wslapshin) 
 */

namespace WS\Domain\Review\Review;
use WS\Domain\ADomain;

class Review extends ADomain
{
    protected $review_id;

    protected $author;
    protected $text;
    protected $rating;
    protected $status;
    protected $date_added;
    protected $date_modified;
    protected $product_id;
    protected $custormer_id;
    
    //additional field
    protected $about;

    protected $product;
    protected $customer;

    public function getMetaData()
    {
        
    }

    public function validate()
    {
        //@task тоже куча лишнего кода кажется,не понятно куда разносить варианты рейтинг в диапазоне,но если null - установить по умолчанию. тут же возвращаются только индексации ошибок а выше нам надо их переводить.
       /* $error = array();
        if (  utf8_strlen($this->get('author')) < 3 || utf8_strlen($this->get('author')) > 64 ){
            $error[] = 'author';
        }

        if (utf8_strlen($this->get('text')) < 1) {
            $error[] = 'text';
        }

        if ( !isset($this->get('rating')) ) {
            $error[] = 'rating';
        }

        if ( $this->get('rating') < 0 || $this->get('rating') > 5) {
            $error[] = 'error_rating';
        }

        return $error;*/
    }
}

