use antsnab;
delete   from category_prodproperty;
delete   from category_prodtab;
delete   from oc_attribute_to_1c;
delete   from oc_cart;
delete   from oc_category;
delete from oc_url_alias where query like 'category%'; 
delete from oc_url_alias where query like 'product%'; 
-- update oc_category set category_id=71 where category_id = 261;
-- update oc_category_description set category_id=71 where category_id=261;
delete   from oc_category_description;
delete   from oc_category_path;
delete from oc_category_to_layout;
delete from oc_category_to_store;
delete   from oc_newsblog_article;
delete   from oc_newsblog_article_description;
delete   from oc_newsblog_article_image;
delete from oc_newsblog_article_related;
delete from oc_newsblog_article_to_store;
delete from oc_newsblog_article_to_layout;
delete   from oc_newsblog_article_to_category;
delete   from oc_newsblog_category;
delete   from oc_newsblog_category_description;
delete   from oc_newsblog_category_path;
delete   from oc_order;
delete from oc_order_total;
delete   from oc_order_history;
delete   from oc_order_custom_field;
delete   from oc_order_product;
delete   from oc_product;
delete   from oc_product_description;
delete   from oc_product_image;
delete   from oc_product_to_category;
delete   from product_prodproperty;
delete   from product_prodtab;
delete from oc_product_analogs;
delete from oc_product_recomends;
delete from oc_product_related;
delete   from produnit_packagestr;
delete   from produnit_template;
delete   from produnit_unit;
delete from oc_review;

-- Вставить вручную корневую директорию